-- Installment purchases. Each instalment is a real transaction in its own
-- competence: the month of the expense shifts monthly and, on a card, so does
-- the invoice it falls into.

alter table public.transactions
  add column installment_group_id uuid,
  add column installment_number   integer,
  add column installment_count    integer;

comment on column public.transactions.installment_group_id is 'Groups the instalments of one purchase. Generated by create_installment_purchase.';
comment on column public.transactions.installment_number is 'Position of this instalment, from 1 to installment_count.';

create index transactions_installment_idx
  on public.transactions (installment_group_id, installment_number)
  where installment_group_id is not null;

alter table public.transactions add constraint transactions_installment_shape check (
  (installment_group_id is null and installment_number is null and installment_count is null)
  or (
    installment_group_id is not null
    and kind = 'EXPENSE'
    and installment_number is not null
    and installment_count is not null
    and installment_count >= 2
    and installment_number between 1 and installment_count
  )
);

-- Splits an amount into instalments in whole cents. The remainder goes to the
-- first instalment, so the instalments always add up to the total.
create or replace function public.split_installment_amounts(total numeric, count integer)
returns numeric[]
language plpgsql
immutable
set search_path = ''
as $$
declare
  cents     bigint;
  base      bigint;
  remainder bigint;
  amounts   numeric[];
begin
  if count is null or count < 2 then
    raise exception 'an installment purchase needs at least 2 instalments'
      using errcode = 'check_violation';
  end if;
  if total is null or total <= 0 then
    raise exception 'an installment purchase needs a positive total'
      using errcode = 'check_violation';
  end if;

  cents := round(total * 100)::bigint;
  if cents < count then
    raise exception 'total % is too small to split into % instalments', total, count
      using errcode = 'check_violation';
  end if;

  base := cents / count;
  remainder := cents - base * count;
  amounts := array_fill(base::numeric / 100, array[count]);
  amounts[1] := (base + remainder)::numeric / 100;
  return amounts;
end;
$$;

-- Same day of the month as `reference`, `months` months later, clamped to the
-- last day of the target month.
create or replace function public.shift_month_day(reference date, months integer)
returns date
language sql
immutable
set search_path = ''
as $$
  select month_start + (least(extract(day from reference)::integer, public.last_day_of_month(month_start)) - 1)
  from (select (date_trunc('month', reference) + (months || ' month')::interval)::date as month_start) as target;
$$;

-- Creates every instalment of a purchase in one statement. Runs with invoker
-- rights, so row level security decides each insert exactly as a direct insert
-- would: VIEW cannot create instalments and MANAGE creates them for the owner.
create or replace function public.create_installment_purchase(
  p_owner_user_id     uuid,
  p_description       text,
  p_total_amount      numeric,
  p_installment_count integer,
  p_date              date,
  p_category_id       uuid,
  p_credit_card_id    uuid default null,
  p_account_id        uuid default null,
  p_household_id      uuid default null,
  p_notes             text default null
)
returns uuid
language plpgsql
set search_path = ''
as $$
declare
  group_id     uuid := gen_random_uuid();
  amounts      numeric[];
  card_closing integer;
  card_due     integer;
  first_due    date;
  month_start  date;
  competence   date;
  on_card      boolean := p_credit_card_id is not null;
  position     integer;
begin
  if on_card = (p_account_id is not null) then
    raise exception 'an installment purchase needs exactly one origin: a card or an account'
      using errcode = 'check_violation';
  end if;

  amounts := public.split_installment_amounts(p_total_amount, p_installment_count);

  if on_card then
    select c.closing_day, c.due_day
      into card_closing, card_due
      from public.credit_cards c
     where c.id = p_credit_card_id
       and c.owner_user_id = p_owner_user_id;

    if not found then
      raise exception 'credit card % does not belong to the transaction owner', p_credit_card_id
        using errcode = 'foreign_key_violation';
    end if;

    first_due := public.invoice_due_date_for(p_date, card_closing, card_due);
  end if;

  for position in 1..p_installment_count loop
    if on_card then
      month_start := (date_trunc('month', first_due) + ((position - 1) || ' month')::interval)::date;
      competence := month_start + (least(card_due, public.last_day_of_month(month_start)) - 1);
    else
      competence := public.shift_month_day(p_date, position - 1);
    end if;

    insert into public.transactions (
      owner_user_id, kind, description, amount, date, due_date, status,
      category_id, account_id, credit_card_id, invoice_due_date, household_id, notes,
      installment_group_id, installment_number, installment_count
    )
    values (
      p_owner_user_id,
      'EXPENSE',
      p_description,
      amounts[position],
      public.shift_month_day(p_date, position - 1),
      case when on_card then null else public.shift_month_day(p_date, position - 1) end,
      case when on_card then 'PAID' else 'PENDING' end::public.transaction_status,
      p_category_id,
      p_account_id,
      p_credit_card_id,
      case when on_card then competence else null end,
      p_household_id,
      p_notes,
      group_id,
      position,
      p_installment_count
    );
  end loop;

  return group_id;
end;
$$;

revoke execute on function public.split_installment_amounts(numeric, integer) from public, anon;
revoke execute on function public.shift_month_day(date, integer) from public, anon;
revoke execute on function public.create_installment_purchase(uuid, text, numeric, integer, date, uuid, uuid, uuid, uuid, text) from public, anon;
grant execute on function public.split_installment_amounts(numeric, integer) to authenticated;
grant execute on function public.shift_month_day(date, integer) to authenticated;
grant execute on function public.create_installment_purchase(uuid, text, numeric, integer, date, uuid, uuid, uuid, uuid, text) to authenticated;
